"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var cors_1 = require("cors");
require("dotenv/config");
var orders_1 = require("./routes/orders");
var error_handler_service_1 = require("./services/error-handler-service");
var app = (0, express_1.default)();
app.use((0, cors_1.default)());
app.use(express_1.default.json());
app.use('/orders', orders_1.orderRouter);
app.use(error_handler_service_1.handleError);
exports.default = app;
